CREATE TABLE zno
(
    year VARCHAR(10),
    outid VARCHAR(40) NOT NULL,
    birth VARCHAR(10) NOT NULL,
    sextypename VARCHAR(40) NOT NULL,
    regname VARCHAR(40) NOT NULL,
    areaname VARCHAR(40) NOT NULL,
    tername VARCHAR(30) NOT NULL,
    regtypename VARCHAR(40) NOT NULL,
    tertypename VARCHAR(40) NOT NULL,
    classprofilename VARCHAR(40),
    classlangname VARCHAR(40),
    eoname VARCHAR(300),
    eotypename VARCHAR(40),
    eoregname VARCHAR(40),
    eoareaname VARCHAR(40),
    eotername VARCHAR(40),
    eoparent VARCHAR(40),
    ukrtest VARCHAR(40),
    ukrteststatus VARCHAR(40),
    ukrball100 NUMERIC(5, 2),
    ukrball12 NUMERIC(5, 2),
    urkball NUMERIC(5, 2),
    ukradaptscale NUMERIC(5, 2),
    ukrptname VARCHAR(40),
    ukrptregname VARCHAR(40),
    ukrptareaname VARCHAR(40),
    ukrpttername VARCHAR(40),
    histtest VARCHAR(40),
    histlang VARCHAR(40),
    histteststatus VARCHAR(40),
    histball100 NUMERIC(5, 2),
    histball12 VARCHAR(40),
    histball NUMERIC(5, 2),
    histptname VARCHAR(40),
    histptregname VARCHAR(40),
    histptareaname VARCHAR(40),
    histpttername VARCHAR(40),
    mathtest VARCHAR(40),
    mathlang VARCHAR(40),
    mathteststatus VARCHAR(40),
    mathball100 NUMERIC(5, 2),
    mathball12 VARCHAR(40),
    mathball NUMERIC(5, 2),
    mathptname VARCHAR(40),
    mathptregname VARCHAR(40),
    mathptareaname VARCHAR(40),
    mathpttername VARCHAR(40),
    phystest VARCHAR(40),
    physlang VARCHAR(40),
    physteststatus VARCHAR(40),
    physball100 NUMERIC(5, 2),
    physball12 VARCHAR(40),
    physball NUMERIC(5, 2),
    physptname VARCHAR(40),
    physptregname VARCHAR(40),
    physptareaname VARCHAR(40),
    physpttername VARCHAR(40),
    chemtest VARCHAR(40),
    chemlang VARCHAR(40),
    chemteststatus VARCHAR(40),
    chemball100 NUMERIC(5, 2),
    chemball12 VARCHAR(40),
    chemball NUMERIC(5, 2),
    chemptname VARCHAR(40),
    chemptregname VARCHAR(40),
    chemptareaname VARCHAR(40),
    chempttername VARCHAR(40),
    biotest VARCHAR(40),
    biolang VARCHAR(40),
    bioteststatus VARCHAR(40),
    bioball100 NUMERIC(5, 2),
    bioball12 VARCHAR(40),
    bioball NUMERIC(5, 2),
    bioptname VARCHAR(40),
    bioptregname VARCHAR(40),
    bioptareaname VARCHAR(40),
    biopttername VARCHAR(40),
    geotest VARCHAR(40),
    geolang VARCHAR(40),
    geoteststatus VARCHAR(40),
    geoball100 NUMERIC(5, 2),
    geoball12 VARCHAR(40),
    geoball NUMERIC(5, 2),
    geoptname VARCHAR(40),
    geoptregname VARCHAR(40),
    geoptareaname VARCHAR(40),
    geopttername VARCHAR(40),
    engtest VARCHAR(40),
    englang VARCHAR(40),
    engteststatus VARCHAR(40),
    engball100 NUMERIC(5, 2),
    engball12 VARCHAR(40),
    engball NUMERIC(5, 2),
    engptname VARCHAR(40),
    engptregname VARCHAR(40),
    engptareaname VARCHAR(40),
    engpttername VARCHAR(40),
    fratest VARCHAR(40),
    fralang VARCHAR(40),
    frateststatus VARCHAR(40),
    fraball100 NUMERIC(5, 2),
    fraball12 VARCHAR(40),
    fraball NUMERIC(5, 2),
    fraptname VARCHAR(40),
    fraptregname VARCHAR(40),
    fraptareaname VARCHAR(40),
    frapttername VARCHAR(40),
    deutest VARCHAR(40),
    deulang VARCHAR(40),
    deuteststatus VARCHAR(40),
    deuball100 NUMERIC(5, 2),
    deuball12 VARCHAR(40),
    deuball NUMERIC(5, 2),
    deuptname VARCHAR(40),
    deuptregname VARCHAR(40),
    deuptareaname VARCHAR(40),
    deupttername VARCHAR(40),
    spatest VARCHAR(40),
    spalang VARCHAR(40),
    spateststatus VARCHAR(40),
    spaball100 NUMERIC(5, 2),
    spaball12 VARCHAR(40),
    spaball NUMERIC(5, 2),
    spaptname VARCHAR(40),
    spaptregname VARCHAR(40),
    spaptareaname VARCHAR(40),
    spapttername VARCHAR(40),
    CONSTRAINT zno_pkey PRIMARY KEY (outid)
)

TABLESPACE pg_default;

ALTER TABLE public.zno
    OWNER to postgres;
INSERT INTO zno VALUES (2020, '1f6c1a4f-8c8a-45c5-bc6c-0eaaeb3a2c30', 2003, 'man', 'ter', 'city', 'region', 'all', 'city', 'historical', 'russian', 'shcool', 'middle', 'ter', 'city', 'area', 'eoparent', 'ukr', 'accept', 157, '9', 62, 0, 'school', 'ter','city', 'area', 'hist', 'russian', 'accept', 137, '8', 37, 'school', 'ter', 'city', 'area', 'math', 'russian', 'unaccept', 0, 'null', 8, 'school', 'ter', 'city', 'area', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);

